name: Node.js CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: cacevedod/pipeline-templates/.github/workflows/nodejs-ci-template.yml@main
    with:
      run-checkov: true
      run-docker: true
