name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  checks: write

jobs:
  template:
    uses: cacevedod/pipeline-templates/.github/workflows/nodejs-ci-template.yml@main
    with:
      run-checkov: true
      run-docker-build: true
